language: node_js
node_js:
  - node

deploy:
  provider: s3
  access_key_id:
    secure: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_ACCESS_KEY
  bucket: "sharksbay1-psprices"
  acl: public_read
  skip_cleanup: true
branches:
  only:
    - master
