language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
script:
  - mkdir -p build/css
  - cp index.html build/
  - ls build
  - yarn run sass
  - yarn run css-preprocess
  - ls build
deploy:
  provider: s3
  access_key_id:
    secure: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_ACCESS_KEY
  bucket: "sharksbay1-psprices"
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
    - master
