deploy:
  provider: s3
  access_key_id:
    secure: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_ACCESS_KEY
  bucket: "sharksbay1-psprices"
  skip_cleanup: true
  region: "us-east-1"
  on:
    branch: master
